version: "3.3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - 2181:2181

  kafka1:
    image: confluentinc/cp-kafka:5.1.0
    container_name: kafka1
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://kafka1:9092
      - KAFKA_LISTENERS=PLAINTEXT_HOST://:9092
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_HOST
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  kafka2:
    image: confluentinc/cp-kafka:5.1.0
    container_name: kafka2
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://kafka2:9093
      - KAFKA_LISTENERS=PLAINTEXT_HOST://:9093
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_HOST
    ports:
      - 9093:9093
    depends_on:
      - zookeeper

  kafka3:
    image: confluentinc/cp-kafka:5.1.0
    container_name: kafka3
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_BROKER_ID=3
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://kafka3:9095
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_HOST
      - KAFKA_LISTENERS=PLAINTEXT_HOST://:9095
    ports:
      - 9095:9095
    depends_on:
      - zookeeper
